In [1]:
import time

import torch

print(torch.__version__)

2.4.0+cpu


In [2]:
x = [1, 2, 3, 4, 5]
x = torch.as_tensor(x)
print(x)

tensor([1, 2, 3, 4, 5])


In [3]:
x = torch.zeros(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
x = torch.ones(3, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
x = torch.full((3, 4), fill_value=2)
print(x)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])


In [11]:
x = torch.randn(3, 4)
print(x)

tensor([[-1.1145,  1.6588,  1.1003,  0.5883],
        [ 0.1633,  0.7731, -0.8294, -1.2050],
        [ 0.1691, -0.0993,  0.9653,  0.8737]])


In [12]:
x = torch.randn(3, 4)
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [13]:
x = torch.randn(3, 4)
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [14]:
x = torch.randn(3, 4)
y = torch.full_like(x, 5)
print(y)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


In [16]:
x = torch.zeros(3, 4, dtype=torch.bool)
print(x)
y = x.new_tensor([1, 2, 3, 4])
print(y)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([True, True, True, True])


In [18]:
x = torch.ones(5, 1)
print(x)
y = torch.ones(1, 5)
print(y)
z = x + y
print(z, z.shape)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])
tensor([[1., 1., 1., 1., 1.]])
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]) torch.Size([5, 5])


In [24]:
x = torch.ones(1, 1, 1, 1, 1)
print(f"x = {x}, shape = {x.shape}")
y = torch.ones(2, 1, 3, 1, 2)
print(f"y = {y}, shape = {y.shape}")
z = x + y
print(z, z.shape)

x = tensor([[[[[1.]]]]]), shape = torch.Size([1, 1, 1, 1, 1])
y = tensor([[[[[1., 1.]],

          [[1., 1.]],

          [[1., 1.]]]],



        [[[[1., 1.]],

          [[1., 1.]],

          [[1., 1.]]]]]), shape = torch.Size([2, 1, 3, 1, 2])
tensor([[[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]],



        [[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]]]) torch.Size([2, 1, 3, 1, 2])


In [27]:
x = torch.ones(3, 4, 5)
print(f"x = {x}, shape = {x.shape}")
print(x.mean())
print(x.mean(-1))

x = tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]), shape = torch.Size([3, 4, 5])
tensor(1.)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [40]:
x = torch.ones(3, 4, 5)
print(f"x = {x}, shape = {x.shape}")
print(x.sum(dim=0))
print(x.sum(dim=(1)))

x = tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]), shape = torch.Size([3, 4, 5])
tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])


In [41]:
x = torch.ones(3, 4, 5)
y = x.sum(dim=(1, 2))
z = x.sum(dim=(1, 2), keepdim=True)
print(y, y.shape)
print(z, z.shape)

tensor([20., 20., 20.]) torch.Size([3])
tensor([[[20.]],

        [[20.]],

        [[20.]]]) torch.Size([3, 1, 1])


In [44]:
x = torch.randn(5, 5)
print(x.to(torch.long))

tensor([[ 0,  0,  0,  0,  0],
        [ 0,  0, -1,  0,  0],
        [-1, -1,  0,  0, -1],
        [ 1,  1, -1,  0,  1],
        [-2,  0, -1,  0, -1]])


In [45]:
x = torch.randn(2, 3, 2)
y = x.view(6, 2)
z = x.view(-1, 2)
print(y, y.shape)
print(z, z.shape)

tensor([[-0.2975, -0.8015],
        [-1.0448, -0.0637],
        [ 0.8427, -1.1848],
        [-0.5508, -2.0639],
        [-0.9893,  0.4755],
        [-1.0159,  1.0103]]) torch.Size([6, 2])
tensor([[-0.2975, -0.8015],
        [-1.0448, -0.0637],
        [ 0.8427, -1.1848],
        [-0.5508, -2.0639],
        [-0.9893,  0.4755],
        [-1.0159,  1.0103]]) torch.Size([6, 2])


In [47]:
x = torch.randn(2, 3, 2)
print(f"x = {x}, shape = {x.shape}")
y = x.permute(1, 2, 0)
print(y, y.shape)

x = tensor([[[ 0.3092,  0.7802],
         [-2.2975,  2.5409],
         [-1.0247,  0.7970]],

        [[ 0.4018, -1.3729],
         [ 0.1376, -0.1295],
         [-1.0010, -0.0097]]]), shape = torch.Size([2, 3, 2])
tensor([[[ 0.3092,  0.4018],
         [ 0.7802, -1.3729]],

        [[-2.2975,  0.1376],
         [ 2.5409, -0.1295]],

        [[-1.0247, -1.0010],
         [ 0.7970, -0.0097]]]) torch.Size([3, 2, 2])


In [48]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.cat([x, y], dim=0)
print(z, z.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([4, 3])


In [ ]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.stack([x, y], dim=1)
print(z, z.shape)

In [ ]:
def add_two_lists(x, y):
    z = []
    for i, j in zip(x, y):
        z.append(i + j)
    return z


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

In [ ]:
def add_two_lists(x, y):
    return x + y


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

In [ ]:
x = torch.randn(3, 3)
y = torch.zeros(5, 2, dtype=torch.long)
print(x.to(torch.float32))
print(x.to(torch.bool))
print(x.to(y))

In [ ]:
x = torch.arange(8)
print(x)
y = torch.arange(2, 8)
print(y)
z = torch.arange(3, 10, step=2)
print(z)